#!/bin/bash

if [[ $EUID -eq 0 ]]
then
  SUDO=
else
  SUDO=sudo
fi

SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"
have_real=$(type -p realpath)
[ "${have_real}" ] && SCRIPT_PATH="$(realpath $SCRIPT_PATH)"

cd "${SCRIPT_PATH}"
[ -f LifeBots/lifebot.sh ] || {
  echo "ERROR: cannot locate LifeBots/lifebot.sh. Exiting."
  exit 1
}

[ -d /usr/local/bin ] || ${SUDO} mkdir -p /usr/local/bin

${SUDO} cp LifeBots/lifebot.sh /usr/local/bin/lifebot
${SUDO} chmod 755 /usr/local/bin/lifebot

[ -d LifeBots/bin ] || {
  echo "ERROR: cannot locate LifeBots/bin/. Exiting."
  exit 1
}

user=$(id -u)
group=$(id -g)
[ -d /usr/local/LifeBots/log ] || ${SUDO} mkdir -p /usr/local/LifeBots/log
${SUDO} touch /usr/local/LifeBots/log/cron.log
${SUDO} chown -R ${user}:${group} /usr/local/LifeBots/log

${SUDO} cp LifeBots/bin/* /usr/local/LifeBots
${SUDO} chmod 755 /usr/local/LifeBots/*
for scr in /usr/local/LifeBots/*
do
  [ "${scr}" == "/usr/local/LifeBots/*" ] && continue
  bas=$(basename "${scr}")
  ${SUDO} rm -f /usr/local/bin/${bas}
  ${SUDO} ln -s ${scr} /usr/local/bin/${bas}
done

printf "\n\nInstallation of the lifebot command and associated scripts is complete.\n"
printf "\nAdd /usr/local/bin to your execution PATH if it is not already included.\n"
printf "\nConfigure lifebot by adding and editing the file ${HOME}/.lifebots"
printf "\n\tSee ${SCRIPT_PATH}/LifeBots/example_dot_lifebots"
printf "\n\tfor a template to use for this file.\n"
printf "\nSee ${SCRIPT_PATH}/LifeBots/crontab.in"
printf "\nfor example crontab entries to schedule bot activities.\n\n"
