#!/bin/bash

usage() {
    printf "\nUsage: mkrelease [-c] [-d] [-p] [-u]"
    printf "\nWhere:"
    printf "\n\t-c indicates clean first"
    printf "\n\t-d indicates create draft release"
    printf "\n\t-p indicates skip package creation step"
    printf "\n\t-u displays this usage message and exits\n"
    exit 1
}

CLEAN=
DRAFT=
PACKAGE=1
BRANCH="main"
while getopts "b:cdpu" flag; do
    case $flag in
        b)
            BRANCH="${OPTARG}"
            ;;
        c)
            CLEAN=1
            ;;
        d)
            DRAFT="--draft"
            ;;
        p)
            PACKAGE=
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

if [ -f LifeBots/VERSION ]; then
  source LifeBots/VERSION
else
  echo "ERROR: missing LifeBots/VERSION"
  exit 1
fi

ANNO="Lifebot release, version ${VERSION}"

if [ -f ${HOME}/.mrprivate ]; then
  source ${HOME}/.mrprivate
else
  echo "ERROR: Could not locate ${HOME}/.mrprivate"
  exit 1
fi

gh release create v${VERSION} ${DRAFT} \
                  --title "${ANNO}" \
                  --target "${BRANCH}" \
                  --notes-file Release_Notes_Lifebot.md \
		  install-lifebot \
                  LifeBots/crontab.in \
                  LifeBots/example_lifebots_notecard \
                  LifeBots/OAuth/4_Refresh_Access_Token.js \
                  LifeBots/OAuth/1_auth_request.js \
                  LifeBots/OAuth/2_authcode_for_access_token.js \
                  LifeBots/OAuth/3_API_Usage.js \
                  LifeBots/LICENSE \
                  LifeBots/bin/easy2clubdj \
                  LifeBots/bin/anya2beach \
                  LifeBots/bin/anya2msdj \
                  LifeBots/bin/anya2club \
                  LifeBots/bin/bots2home \
                  LifeBots/bin/bots2clubdance \
                  LifeBots/bin/angelus2pole \
                  LifeBots/bin/checkbots \
                  LifeBots/bin/easy2pole \
                  LifeBots/bin/checkeasy \
                  LifeBots/bin/angelus2clubdj \
                  LifeBots/bin/anya2seat \
                  LifeBots/example_dot_lifebots \
                  LifeBots/VERSION \
                  LifeBots/Examples/LifeBot_Logout.lsl \
                  LifeBots/Examples/LifeBot_Login.lsl \
                  LifeBots/Examples/logout-curl.sh \
                  LifeBots/Examples/login-curl.sh \
                  LifeBots/lifebot.sh \
                  LifeBots/Developer_Getting_Started.txt

git fetch --tags origin
